dist: bionic
sudo: required
language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install autoconf automake autopoint libtool libpam0g-dev bison flex gettext
  - sudo apt-get install gcc
  - sudo apt-get install clang
  - sudo apt-get install musl musl-dev musl-tools
matrix:
  include:
    - name: "amd64 / gcc / glibc / dynamic"
      arch: amd64
      os: linux
      env:
         - CC="gcc"
         - DISTCHECK_CONFIGURE_EXTRA_FLAGS="--enable-werror"
         - TRAVIS_CHECK_KEYWORDS='unittest e2e'
         - TRAVIS_SANDBOX='priviliged'
    - name: "amd64 / gcc / glibc / dynamic"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      os: linux
      env:
         - CC="gcc"
         - DISTCHECK_CONFIGURE_EXTRA_FLAGS="--enable-werror"
         - TRAVIS_CHECK_KEYWORDS='unittest e2e'
         - TRAVIS_SANDBOX='priviliged'
    - name: "amd64 / clang / libclang / dynamic"
      arch: amd64
      os: linux
      env:
         - CC="clang"
         - DISTCHECK_CONFIGURE_EXTRA_FLAGS="--enable-werror"
         - TRAVIS_CHECK_KEYWORDS='unittest e2e'
         - TRAVIS_SANDBOX='priviliged'
    - name: "amd64 / clang / libclang / dynamic"
      arch: arm64-graviton2
      virt: lxd
      group: edge
      os: linux
      env:
         - CC="clang"
         - DISTCHECK_CONFIGURE_EXTRA_FLAGS="--enable-werror"
         - TRAVIS_CHECK_KEYWORDS='unittest e2e'
         - TRAVIS_SANDBOX='priviliged'

script:
  - ./tests/travis-ci-run
